package com.ionhex975.vulkanpostfx.client.runtime.nativevpfx;

public enum VpfxNativeFailureStage {
	NONE,
	EXECUTE_FLAG_DISABLED,
	NOT_RENDER_THREAD,
	MAIN_TARGET_UNAVAILABLE,
	INVALID_MAIN_TARGET_DIMENSIONS,
	TRANSIENT_TARGET_CREATE,
	COPY_MAIN_TO_TRANSIENT,
	USER_PIPELINE_RESOLVE,
	USER_PIPELINE_CREATE,
	USER_SHADER_DRAW,
	BUILTIN_PIPELINE_CREATE,
	BUILTIN_FALLBACK_DRAW,
	NATIVE_DRAW_FAILED,
	POSTCHAIN_FALLBACK
}
